- hosts: telnet
  gather_facts: false
  connection: local
  tasks:
  - name: run show command
    ansible.netcommon.telnet:
      send_newline: true
      timeout: 5
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      port: "{{ ansible_port }}"
      prompts:
      - '[>#]'
      command:
      - terminal length 0
      - show version
      
    register: output

  - name: Display output
    ansible.builtin.debug:
      var: output.stdout_lines
      